#set($d = '$')
spring:
  docker:
    compose:
      file: ${d}{DOCKER_COMPOSE_FILE:../../compose.yaml}
      lifecycle-management: start-only
      readiness:
        timeout: 2m
  kafka:
    bootstrap-servers: ${d}{SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: ${rootArtifactId}-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "${package}.adapters.inbound.kafka.message"
        spring.json.value.default.type: ${package}.adapters.inbound.kafka.message.CustomerRegisteredKafkaMessage
        spring.json.use.type.headers: false

customer:
  registration:
    topic: customer-registered-events
    kafka:
      enabled: true

${rootArtifactId}:
  client:
    url: ${d}{APPX_SERVICE_CLIENT_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
